### PR TITLE
Add whats_where command, heroic command, add context for replied messages

### PR DESCRIPTION
**Pull request by hahayupgit**
### Aliases:
- `whatswhere` & `where`
   - Replies with all locations listed on the [docs](https://docs.getwhisky.app/paths.html)
Screenshot 2024-05-03 at 11 59 47 AM

- `gptk`, `bottles`, `logs`, and `whiskycmd`
   - Replies with specific paths for each command.
Screenshot 2024-05-03 at 12 00 16 PM

## `heroic` command
- Replies with information on how to use Whisky within Heroic.
Screenshot 2024-05-07 at 3 25 49 PM

### Aliases:
- `epic`, `gog`, `amazon`, `prime`
   - Replies with specific heading instructions for each store.
   - Screenshot 2024-05-07 at 3 26 20 PM

## Updated functionality: Parent Replies
Commands that are called while replying to a person will now show who invoked the original command. This applies to `discord`, `does_my_game_work`, `game_support`, `github`, `username`, `website`, and `whats_where`. Also changes the reply function to enable pings to the person replied to.
Screenshot 2024-05-03 at 12 01 28 PM

### CODE REVIEW

**Comment by hahayupgit** [comment]
Also ignore that `Add default reply for ~gs` that was an old commit that doesn't actually change anything

**Comment by hahayupgit** [comment]
ALSO the slash commands for the custom `whats_where` aliases doesn't work because I would have to create 4 new commands for each but the base command still works

**Comment by JoshuaBrest** [comment]
@hahayupgit The `GPTK` naming convenction is deprecated. Please refer to it as `WhiskyWine`.

**Comment by hahayupgit** [comment]
fixed! 👍

**Comment by IsaacMarovitz** [comment]
@hahayupgit Please rebase when you have the time

**Comment by hahayupgit** [comment]
I'll request a review when I'm finished!

**Comment by hahayupgit** [comment]
@IsaacMarovitz okay, should be good now

**Review by IsaacMarovitz — APPROVED** [review]

**Pull request merged**
